services:
  db:
    container_name: pg-product
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: myproductDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    container_name: pg-adminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"
volumes:
 postgres_data:


  